# Generated by Django 2.1.5 on 2019-02-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_use', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
