# Generated by Django 2.1.5 on 2019-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point_use', '0002_auto_20190203_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbr_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('mdn_no', models.CharField(max_length=12)),
                ('birthday', models.CharField(max_length=8)),
                ('mbr_sts', models.CharField(choices=[('A', 'available member'), ('R', 'retired member')], max_length=10)),
                ('last_sales_date', models.DateTimeField()),
            ],
        ),
    ]
