# Generated by Django 2.1.5 on 2019-02-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_use', '0003_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
