# Generated by Django 2.1.5 on 2019-02-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_use', '0005_card_member_merchant_point_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slp_cd',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ans_cd',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ans_msg',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rmn_pnt',
            field=models.IntegerField(default=0),
        ),
    ]
